apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-kavalan-sa
  namespace: default
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   annotations:
#     kubernetes.io/enforce-mountable-secrets: "true"
#   name: my-serviceaccount
#   namespace: my-namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-kavalan-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-kavalan-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-kavalan-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-kavalan-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Deployment
metadata:
  name: pod-kavalan-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-kavalan
  template:
    metadata:
      labels:
        app: pod-kavalan
    spec:
      serviceAccountName: pod-kavalan-sa
      containers:
      - name: pod-kavalan-container
        image: nginx:latest
        ports:
        - containerPort: 80
